### ISSUE TITLE
Fix bug in CI

### ISSUE THREAD

**Issue by lightclient** [protolambda/mergemock#39]
Seems to happen occasionally on both the unit tests and the integration test.

```
SIGILL: illegal instruction
PC=0xb660d7 m=5 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xdd 0x66 0x4d 0xf 0x38 0xf6 0xe1 0xc4 0x62 0xd3 0xf6

goroutine 16 [syscall]:
runtime.cgocall(0xb46620, 0xc000175750)
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/cgocall.go:157 +0x5c fp=0xc000175728 sp=0xc0001756f0 pc=0x4219fc
github.com/supranational/blst/bindings/go._Cfunc_blst_keygen(0xc0000393e0, 0xc0000393c0, 0x20, 0x0, 0x0)
	_cgo_gotypes.go:372 +0x45 fp=0xc000175750 sp=0xc000175728 pc=0x891745
github.com/supranational/blst/bindings/go.KeyGen({0xc0000393c0, 0x20, 0x13bec40?}, {0x0, 0x0, 0xcb7e20?})
	/home/runner/go/pkg/mod/github.com/supranational/blst@v0.3.7/bindings/go/blst.go:135 +0x9c fp=0xc000175790 sp=0xc000175750 pc=0x8941fc
github.com/prysmaticlabs/prysm/crypto/bls/blst.RandKey()
	/home/runner/go/pkg/mod/github.com/prysmaticlabs/prysm@v1.4.2-0.20220515031444-3d3890205f40/crypto/bls/blst/secret_key.go:32 +0xae fp=0xc000175818 sp=0xc000175790 pc=0x8d5f8e
main.(*ConsensusCmd).Run(0xc0000a5200, {0xe90330?, 0xc000318200?}, {0x0?, 0xc000322300?, 0x20?})
	/home/runner/work/mergemock/mergemock/consensus.go:116 +0x356 fp=0xc000175950 sp=0xc000175818 pc=0xb17b56
github.com/protolambda/ask.(*CommandDescription).Execute(0xc00009a980, {0xe90330, 0xc000318200}, 0x0?, {0xc000132140, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/protolambda/ask@v0.1.2/ask.go:574 +0x6e7 fp=0xc000175c60 sp=0xc000175950 pc=0xb02727
github.com/protolambda/ask.(*CommandDescription).Execute(0xc00009a900, {0xe90330, 0xc000318200}, 0x0?, {0xc000132130, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/protolambda/ask@v0.1.2/ask.go:476 +0x1b3 fp=0xc000175f70 sp=0xc000175c60 pc=0xb021f3
main.main.func2()
	/home/runner/work/mergemock/mergemock/main.go:64 +0x85 fp=0xc000175fe0 sp=0xc000175f70 pc=0xb20e85
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000175fe8 sp=0xc000175fe0 pc=0x489301
created by main.main
	/home/runner/work/mergemock/mergemock/main.go:63 +0x1d1

goroutine 1 [select]:
main.main()
	/home/runner/work/mergemock/mergemock/main.go:69 +0x245

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:63 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55 +0x75

goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:63 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55 +0x75
text/template/parse.(*lexer).run(0xc0001961b0)
	/opt/hostedtoolcache/go/1.18.1/x64/src/text/template/parse/lex.go:236 +0x2a
created by text/template/parse.lex
	/opt/hostedtoolcache/go/1.18.1/x64/src/text/template/parse/lex.go:229 +0x1ca

goroutine 22 [runnable]:
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55 +0x75

goroutine 23 [runnable]:
github.com/ethereum/go-ethereum/core.newTxSenderCacher.func1()
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/core/tx_cacher.go:55 +0x75

goroutine 24 [runnable]:
github.com/ethereum/go-ethereum/metrics.NewMeterForced.func2()
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/metrics/meter.go:71
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/metrics/meter.go:71 +0xc5

goroutine 25 [runnable]:
github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer.func1()
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/consensus/ethash/sealer.go:263
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
	/home/runner/go/pkg/mod/github.com/!marius!van!der!wijden/go-ethereum@v1.8.22-0.20220316185917-87d642df3e87/consensus/ethash/sealer.go:263 +0x319

goroutine 30 [runnable]:
os/signal.loop()
	/opt/hostedtoolcache/go/1.18.1/x64/src/os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.18.1/x64/src/os/signal/signal.go:151 +0x2a

rax    0x76882064825eacc9
rbx    0xea8700
rcx    0xea86a0
rdx    0x2b6cedcb87925c23
rdi    0x7fdac6e76d70
rsi    0x7fdac6e76cf0
rbp    0xa927ec58accde979
rsp    0x7fdac6e76b58
r8     0xfffffffeffffffff
r9     0x24d155bab99d4de5
r10    0xbd68c647da15337
r11    0x73e101ba300e2e2
r12    0x1a9a59b6e3dfd32c
r13    0x82c6e84dcba41755
r14    0x4c53b4b266e739ce
r15    0x0
rip    0xb660d7
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by lightclient** [comment]
Seems like this has something to do with the bls library using an illegal instruction. I'm guessing it's only sporadic, because some of the machines that the CI runs on _actually_ support the instruction whereas some don't.
